from __future__ import annotations

BUSINESSES = ["Unica", "HDN Integrated Farm"]
INVENTORY_TYPES = ["Unica Perishable", "Unica Non-Perishable", "HDN Warehouse", "HDN Plants"]
ASSET_STATUSES = [
    "Good Condition",
    "Fair Condition",
    "Poor Condition",
    "Functional",
    "Not Functional",
]
ASSET_TYPES = [
    "Equipment",
    "Tools",
    "Misc",
    "Seeds/Plants/Planting Tools",
    "Safety Gear",
    "Fertilizers/Chemicals",
    "Plumbing",
    "Livestock Items",
    "Cooking Materials",
]
DEFAULT_LOW_STOCK_LEVEL = 5

DEFAULT_PRODUCTS = [
    ("Arla Milk", "MILK & YOGURT"),
    ("Condensed Milk", "MILK & YOGURT"),
    ("Evap Milk", "MILK & YOGURT"),
    ("Oat Side", "MILK & YOGURT"),
    ("Yogurt", "MILK & YOGURT"),
    ("Brown Sugar Sachet", "COFFEE"),
    ("Creamer", "COFFEE"),
    ("Black Magic", "COFFEE"),
    ("Brazil Cerrado", "COFFEE"),
    ("Nescafe", "COFFEE"),
    ("Rice Coffee Granule", "COFFEE"),
    ("Cat's Whiskers", "HERB TEA"),
    ("Tsaang Gubat", "HERB TEA"),
    ("Banaba", "HERB TEA"),
    ("Roselle", "HERB TEA"),
    ("Holy Basil", "HERB TEA"),
    ("Blue Ternate", "HERB TEA"),
    ("Peppermint", "HERB TEA"),
    ("Blueberry Puree", "PUREE"),
    ("Kiwi Pure", "PUREE"),
    ("Strawberry Puree", "PUREE"),
    ("Caramel Syrup", "SYRUP"),
    ("Food Color Red", "SYRUP"),
    ("Green Apple Syrup", "SYRUP"),
    ("Hazelnut Syrup", "SYRUP"),
    ("Lemon Syrup", "SYRUP"),
    ("Passionfruit Syrup", "SYRUP"),
    ("Peach Syrup", "SYRUP"),
    ("Popcorn Syrup", "SYRUP"),
    ("Raspberry Syrup", "SYRUP"),
    ("Sprite", "SYRUP"),
    ("Strawberry Syrup", "SYRUP"),
    ("Rose Syrup", "SYRUP"),
    ("Salted Caramel Syrup", "SYRUP"),
    ("Sugar Syrup", "SYRUP"),
    ("Vanilla Syrup", "SYRUP"),
    ("Pandan Syrup", "SYRUP"),
    ("Gourmet Syrup", "SYRUP"),
    ("Chocolate Powder", "POWDER & CREAM"),
    ("Frappe Powder", "POWDER & CREAM"),
    ("Matcha Powder", "POWDER & CREAM"),
    ("Whipped Cream", "POWDER & CREAM"),
    ("Tablea", "POWDER & CREAM"),
    ("Oreo", "POWDER & CREAM"),
    ("Caramel Sauce", "SAUCE"),
    ("Chocolate Sauce", "SAUCE"),
    ("Cold Cups", "CUPS & STRAWS"),
    ("Disposable Cup", "CUPS & STRAWS"),
    ("Disposable Fork", "CUPS & STRAWS"),
    ("Dome Lid", "CUPS & STRAWS"),
    ("Double Plastic", "CUPS & STRAWS"),
    ("Flat Lid", "CUPS & STRAWS"),
    ("Hot Cups", "CUPS & STRAWS"),
    ("Lid for Hot Cups", "CUPS & STRAWS"),
    ("Paper Bag (Big)", "CUPS & STRAWS"),
    ("Paper Bag (Small)", "CUPS & STRAWS"),
    ("Paper Straw", "CUPS & STRAWS"),
    ("Sauce Cup", "CUPS & STRAWS"),
    ("Single Plastic", "CUPS & STRAWS"),
    ("Stirrer", "CUPS & STRAWS"),
    ("Take Out Box  Small", "CUPS & STRAWS"),
    ("Take Out Box  Big", "CUPS & STRAWS"),
    ("Tissue", "CUPS & STRAWS"),
    ("Carrot Cake", "CAKES"),
    ("Cheesecake", "CAKES"),
    ("Choco Moist Cake", "CAKES"),
    ("Red Velvet Cake", "CAKES"),
    ("Tiramisu Cake", "CAKES"),
    ("Ube Cake", "CAKES"),
    ("Chocolate Chip Cookie", "COOKIES"),
    ("Mallow Crunch Cookie", "COOKIES"),
    ("Oatmeal Raisin Cookie", "COOKIES"),
    ("Red Velvet Cookie", "COOKIES"),
    ("Rocky Road Cookie", "COOKIES"),
    ("Slutty Brownies", "BARS"),
    ("Revel Bars", "BARS"),
]
